name: build-ci-2.0

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32, esp8266]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install platformIO
        run: bash ./.github/ci/install-platformio.sh

      - name: Build platformIO
        run: bash ./.github/ci/build-esp3d.sh ${{ matrix.target }} pio

      - name: List files
        run: ls -latr

      - name: Tree files
        run: tree -a .pioenvs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp3d-${{ matrix.target }}.bin
          path: ./.pioenvs/${{ matrix.target }}/firmware.bin

